baseURL = 'https://pdzeng.com'
languageCode = 'en-us'
title = 'pandatalk'

# disqusShortname = "pandatalk" # "seven-demo"

# [mediaTypes.'application/x-ndjson']
# suffixes = ['ndjson']

[outputs]
# home = ["HTML", "Algolia"]

# [outputFormats]
# [outputFormats.Algolia]
# baseName = 'algolia'
# isPlainText = true
# notAlternative = true
# mediaType = 'application/x-ndjson'

[Params]
description = "panda's talk"
enableSearch = false         # 是否開放搜尋功能
omitCategoryOnMenu = false   # Menu 中 Category 的分類
categoryName = "Category"
showCodeCopyButton = true

disableToTop = true
disableToBottom = false

[Params.logo]
img = "/images/logo.svg"
img_dark = "/images/logo.svg"

# max height not greater than 56 (px). default: 56 (px)
customLogoHeight = '56'
customLogoWidth = '120'

[Params.app]
# 是否配置 favicon
noFavicon = false
# 使用的现代SVG favicon，用于替换旧式的.png和.ico文件
svgFavicon = "/favicon.svg"
iconColor = "#ffffff"
themeColor = "#ffffff"


[Params.head]
# Put custom css file in the assets folder, not in the static folder.
# customCSS = "css/custom.css"

[Params.home]
# Customize the type of content to display up-to-date, 
# and display all content with 'IsPage=true' if not.
# eg: showContentTypes = ["posts", "blogs"]
showContentTypes = ["posts", "doc"]

[Params.society]
[Params.society.email]
enable = true
url = "pandap.d819@gmail.com"
[Params.society.github]
enable = true
url = "https://github.com/panda850819"
[Params.society.facebook]
enable = true
url = "https://www.facebook.com/pdzeng/"
[Params.society.x] # old twitter
enable = true
url = "https://www.twitter.com/pandazeng1"
# [Params.society.wechat]
# enable = true
# OrcodeUrl = ["微信二维码图片地址1", "微信二维码图片地址2"]


# Copyright 
[Params.copyright]
owner = "Panda"
start_year = "2024"

# Article Meta
[Params.articleMeta]
enableAuthor = false
disableDate = false
disableModifiedDate = false
disableCountWords = false
disableReadTime = false
disableHero = false
disableToc = false

# Note: only works if waline or twikoo is enabled.
enablePageView = true

# Comments
# [Params.comment]
# enable = true
# # Note: only works if waline or twikoo is enabled.
# enableCounts = true
# [Params.comment.waline]
# enable = true
# serverURL = "https://seven-demo.comment.supcat.cn/.netlify/functions/comment"
# lang = "en"
# reaction = true
# search = true
# [Params.comment.twikoo]
# enable = false
# envID = "https://celebrated-youtiao-8a8d79.netlify.app/.netlify/functions/twikoo"
# path = ""
# lang = "en"
# region = ""

# Analytics
[Params.analytics]
[Params.analytics.goatcounter]
enable = true
code = "seven-demo"

[markup]
[markup.goldmark]
[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false
[markup.goldmark.parser.attribute]
block = false

[markup.tableOfContents]
endLevel = 3
startLevel = 2

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[menu]
[[menu.main]]
name = "Doc"
pre = ""
url = "/doc/"
weight = 10
[[menu.main]]
name = "Posts"
pre = "pen-tool"
url = "/posts/"
weight = 20
[[menu.main]]
name = "Archive"
url = "/archive"
weight = 30
[[menu.main]]
name = "Goods"
pre = ""
url = "/goods/"
weight = 40
# [[menu.main]]
# name = "Releases"
# pre = "releases"
# weight = 50
# [[menu.main]]
# identifier = "comments-with-waline"
# name = 'with waline'
# url = 'https://seven-demo.supcat.cn/'
# parent = 'Releases'
# weight = 1
# [[menu.main]]
# name = 'with twikoo'
# url = 'https://seven-demo-with-twikoo.netlify.app/'
# parent = 'Releases'
# weight = 2

[module]
# Recommend Chinese users to use this proxy configuration
# proxy = 'https://goproxy.cn,direct'
[[module.imports]]
path = 'github.com/mrhelloboy/seven'
[module.hugoVersion]
extended = false
min = "0.112.0"
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"

[build]
writeStats = true
[[build.cachebusters]]
source = "assets/watching/hugo_stats\\.json"
target = "styles\\.css"
[[build.cachebusters]]
source = "(postcss|tailwind)\\.config\\.js"
target = "css"
[[build.cachebusters]]
source = "assets/.*\\.(js|ts|jsx|tsx)"
target = "js"
[[build.cachebusters]]
source = "assets/.*\\.(.*)$"
target = "$1"
